SchoolAutomation/Home/urls.py
from django.conf.urls import url
from .views import *
from django.shortcuts import redirect

urlpatterns = [
	url(r'^$', index, name='Home/index'),
	url(r'^index', index, name='Home/index'),
	url(r'^admin', lambda _: redirect('admin:index'), name='Home/admin'),
	url(r'AdmissionForm', new_form, name='Home/admissionform'),
	url(r'^resultadminlist', ResultAdminListView.as_view(), name='Automation/resultadminlist'),
	url(r'^resultadmincreate', createresultadmin, name='Automation/createresultadmin'),
	url(r'^resultadminprofile', resultadminprofile, name='Automation/resultadminprofile'),
]

SchoolAutomation/SchoolAutomation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('Automation/', include('Automation.urls', 'Automation')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SchoolAutomation/Home/models.py
from django.db import models
import datetime
from django.urls import reverse

# Create your models here.
Gender = (
    ('Male', 'Male'),
    ('Female', 'Female'),
)
BLOOD_GROUP = (
    ('A+', 'A+'),
    ('A-', 'A-'),
    ('B-', 'B-'),
    ('AB-', 'AB-'),
    ('AB+', 'AB+'),
    ('O+', 'O+'),
    ('O-', 'O-'),
)
Medium = (
    ('Bangla', 'Bangla'),
    ('English', 'English'),
)
CLASS = (
    ('Six', 'VI'),
    ('Seven', 'VII'),
    ('Eight', 'VIII'),
    ('Nine', 'IX'),
    ('Ten', 'X'),
)
SOUGHT_CLASS = (
    ('Six', 'VI'),
    ('Seven', 'VII'),
    ('Eight', 'VIII'),
    ('Nine', 'IX'),
    ('Ten', 'X'),
)
RELIGION = (
    ('Islam', 'Islam'),
    ('Hindu', 'Hinduism'),
    ('Buddha', 'Buddhaism'),
    ('Christian', 'Christian'),
    ('Other', 'Other')
)
QUALIFICATION = (
    ('SSC', 'SSC'),
    ('HSC', 'HSC'),
    ('Honors', 'Honors'),
    ('Masters', 'Masters'),
    ('Others', 'Others'),
)


def current_date():
    return datetime.date.today().year


class Admission(models.Model):

    first_name = models.CharField(max_length=50, blank=False, verbose_name='First Name')
    last_name = models.CharField(max_length=50, blank=False, verbose_name='Last Name')
    Class = models.CharField(default='VI', choices=SOUGHT_CLASS, blank=False,
                             max_length=100, verbose_name='Sought Admission in')
    medium = models.CharField(default='Bangla', choices=Medium, blank=False,
                              max_length=100, verbose_name='Medium')
    gender = models.CharField(default='Male', choices=Gender,
                              max_length=20, blank=False, verbose_name='Gender')
    height = models.FloatField(
        default='5.3', blank=False, verbose_name='Height')
    weight = models.FloatField(
        default='45.2', blank=False, verbose_name='Weight')
    blood = models.CharField(default='A+', max_length=20, choices=BLOOD_GROUP,
                             blank=False, verbose_name='Blood Group')
    dob = models.DateField(blank=False,  # default=datetime.date.today,
                           verbose_name='Date of Birth')
    religion = models.CharField(default='Islam', choices=RELIGION, blank=False,
                                max_length=100, verbose_name='Religion')
    father_first_name = models.CharField(
        max_length=50, blank=False, verbose_name='Father Name (First)')
    father_last_name = models.CharField(
        max_length=50, blank=False, verbose_name='Father Name (Last)')
    fathers_qualification = models.CharField(default='SSC',
                                             choices=QUALIFICATION, blank=False, max_length=100, verbose_name='Fathers (Qualification)')
    father_occupation = models.CharField(max_length=50, blank=False, verbose_name='Occupation')
    father_phone = models.IntegerField(blank=False, verbose_name='Mobile')
    mother_first_name = models.CharField(
        max_length=50, blank=False, verbose_name='Mother Name (Frist)')
    mother_last_name = models.CharField(
        max_length=50, blank=False, verbose_name='Mother Name (Last)')
    mothers_qualification = models.CharField(default='SSC',
                                            choices=QUALIFICATION, blank=False, max_length=100, verbose_name='Mothers (Qualification)')
    mother_occupation = models.CharField(max_length=50, blank=False, verbose_name='Occupation')
    moher_phone = models.IntegerField(blank=False, verbose_name='Mobile')
    address = models.CharField(default='Uttara', max_length=200,
                               blank=False, verbose_name='Address')
    last_class = models.CharField(default='VI', choices=CLASS, max_length=100,
                                  blank=False, verbose_name='Last Class Attended')
    last_school = models.CharField(default='Milestone', blank=False,
                                   max_length=100, verbose_name='Last School')
    session = models.IntegerField(default=current_date, verbose_name='Session')
    approved = models.BooleanField(default='False', blank='True')
    is_student = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return self.first_name

SchoolAutomation/Home/forms.py
from django import forms
from .models import Admission


class AdmissionForm(forms.ModelForm):

	class Meta:
		model = Admission
		fields = "__all__"
		exclude = ['approved', 'session', 'is_student']


class ApproveForm(forms.ModelForm):
	first_name = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
	last_name = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
	Class = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
	medium = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
	gender = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
	religion = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
	father_first_name = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
	father_last_name = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
	fathers_qualification = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
	father_occupation = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
	father_phone = forms.IntegerField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
	mother_first_name = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
	mother_last_name = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
	mothers_qualification = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
	mother_occupation = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
	moher_phone = forms.IntegerField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
	last_class = forms.IntegerField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
	last_school = forms.IntegerField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))

	class Meta:
		model = Admission
		fields = "__all__"
		exclude = ['blood', 'height', 'weight', 'dob', 'address', 'session', 'is_student']

SchoolAutomation/Home/views.py
from django.contrib import messages
from django.shortcuts import render
from django.http import HttpRequest
from datetime import datetime
from .forms import AdmissionForm
from Automation.models import ResultOfficer
from django.views.generic import ListView
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect


# Create your views here.

def resultadmin_required(user):
	if user:
		return user.groups.filter(name='ResultAdmin').count() == 1
	return False


def admin_required(user):
	if user.is_superuser:
		return True
	return False


def index(request):
	"""Renders the home page."""
	assert isinstance(request, HttpRequest)
	return render(
		request,
		'Home/index.html',
		{
			'title': 'Home Page',
			'year': datetime.now().year,
		}
	)


def new_form(request):
	if request.method == "POST":
		form = AdmissionForm(request.POST)
		if form.is_valid():
			post = form.save(commit=True)
			post.save()
			messages.success(request, 'Your Application Submitted Succesfully')
			form = AdmissionForm()
	else:
		form = AdmissionForm()
	return render(request, 'Home/admissionform.html', {'form': form})


class ResultAdminListView(ListView):
	queryset = ResultOfficer.objects.all()


@login_required(login_url='/Automation/login/')
@user_passes_test(admin_required, login_url='/Automation/login')
def createresultadmin(request):
	if request.method == 'POST':
		firstname = request.POST['firstname']
		lastname = request.POST['lastname']
		phone = request.POST['phone']
		email = request.POST['email']
		address = request.POST['address']
		password = 'milestone123'
		form = ResultAdmin.objects.create(
			first_name=firstname,
			last_name=lastname,
			email=email,
			address=address,
			phone_no=phone,
		)
		user = User.objects.create_user(email, email, password)
		user.save()
		group = Group.objects.get(name='ResultAdmin')
		group.user_set.add(user)
		messages.success(request, 'Result Admin Added Succesfully')
		form.save()
		return redirect('/resultadminlist')
	return render(request, 'Automation/resultadmincreate.html', {'title': 'Create Result Admin'})


@login_required(login_url='/Automation/login/')
@user_passes_test(resultadmin_required, login_url='/Automation/login')
def resultadminprofile(request):
	teacher = ResultOfficer.objects.get(email=request.user)
	user = User.objects.get(username=request.user)
	return render(request, 'Automation/resultadminprofile.html', {'teacher': teacher, 'user': user})

SchoolAutomation/templates/Home/admissionform.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Online Admission Form</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/gijgo/1.9.11/combined/css/gijgo.min.css"></link>
    <link rel="stylesheet" href="{% static 'css/admissionform.css' %}"/>
</head>
<body>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}> {{ message }} </li>
    {% endfor %}
</ul>
{% endif %}
 <div class="container fluid">
     <h3 align="center" style="border-bottom: 2px solid blue">Application Form</h3>
    <form method="post" class="post-form">{% csrf_token %}
        <div align="center" width="600px">
            <table class="table-bordered" width="600px">
            {{form.as_table}}
                </table>
        </div>

        <br>
        <div align="center">
            <button type="submit" class="save btn btn-default button" style="margin-right:25px">Save</button>
           <a class="btn btn-default button" href="{% url 'Home/index'%}" style="margin-left:25px">Back</a>
        </div>
    </form>
 </div>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/gijgo/1.9.11/combined/js/gijgo.min.js "></script>
<script>
  $( function() {
    $( "#id_dob" ).datepicker();
  } );
  </script>
</body>
</html>

SchoolAutomation/templates/Home/index.html
  <!DOCTYPE html>
  {% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Milestone School</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}" media="screen"/>
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
  </head>
    <body>
      <!-- Header -->
      <div class="banner">
    <header>
      <div class="hat">
        <h1><i class="fas fa-graduation-cap"></i><span class="title-color">Milestone</span></h1>
      </div>
      <div class="search_my">
        <form>
          <input type="search" class="search1" placeholder="search">
          <button class="button1" type="submit"><i class="fas fa-search"></i></button>
        </form>
      </div>
      <div class="clearfix"></div>
    </header>
    <!-- Nav bar -->
    <div class="nav1">
    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-default">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav m-auto">
      <li class="nav-item"><a class="nav-link" href="#">Home</a></li>
      <li class="nav-item"><a class="nav-link" href="#">Gallery</a></li>
      <li class="nav-item dropdown">
        <a class="nav-link" href="{% url 'Home/admissionform' %}">Online Admission</a>
      </li>
      <li class="nav-item"><a class="nav-link" href="{% url 'Automation:Automation/index' %}">Automation</a></li>
      <li class="nav-item"><a class="nav-link" href="#">About</a></li>
      <li class="nav-item"><a class="nav-link" href="#">Contact</a></li>
    </ul>
  </div>
</nav>
</div>
</div>
<section class="container slider">
        <div class="flexslider">
          <ul class="slides">
            <li class="flex-caption">

              <button type="button" class="more-bttn" data-toggle="modal" data-target="#exampleModalCenter">
                Read More
              </button>
  	    		</li>
  	    		<li class="flex-caption">
              <button type="button" class="more-bttn" data-toggle="modal" data-target="#exampleModalCenter">
                Read More
              </button>
  	    		</li>
  	    		<li class="flex-caption">
              <button type="button" class="more-bttn" data-toggle="modal" data-target="#exampleModalCenter">
                Read More
              </button>
  	    		</li>
  	    		<li class="flex-caption">
              <button type="button" class="more-bttn" data-toggle="modal" data-target="#exampleModalCenter">
                Read More
              </button>
  	    		</li>
          </ul>
        </div>
      </section>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <img src="#" />
      <p>hello world</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
  </div>

<!-- About -->
  <div class="container">
    <div class="about">
      <h1>ABOUT</h1>
      <h3>What we are</h3>
      <p style="text-align:justify">We, a number of educationists, had been discussing for a long time about the establishment
        of an educational institution of international standard. Among us, some have worked and are
        still working in universities and the others have worked at renowned colleges and cadet colleges
        as professors & principals. In the light of our long experience, we have perceived that our children,
       despite securing good results and being meritorious, cannot attain the expected results because of
       excessive coyness. They are introvert; they know but cannot express their thoughts. Moreover,
       having completed their education in Bangla Medium, most of these students remain weak in writing and
       speaking in English. As a result, when they go abroad for higher studies, they fall in deep water.
       Even in our own country, they fail to get a good job in the multinational companies.</p>

      <p style="text-align:justify">On the other hand, our students attending the British Education curriculum, i.e. the students of ‘O’ level & ‘A’ level
         face a great hardship while competing for admission in the BUET, Public Universities, Medical Colleges, etc.
         These students have segregated themselves from the age-old traditions & customs in respect of dress, way of life,
         food habits and manners. This is mainly due to the British curriculum followed at ‘O’ & ‘A’ level Exams.
          Where our students are taught British culture, heritage & tradition. They leran British history, geography, economy,
         way of life etc. but not those of Bangladesh.</p>

     <p style="text-align:justify">Against this backdrop of confusion and disorder in the education system of the country, we ventured to establish an
        ideal educational institution in the year 2001 named Milestone College at Gareeb-e-Newaz Avenue, Sector 11 of Uttara Model Town, Uttara, Dhaka 1230.
         The building where we started is owned by Milestone family and now it is used as the Headquarters of Milestone.</p>
<b><p style="text-align:justify">Govt. Approval:</p></b>
<p style="text-align:justify">Milestone College is approved by the Ministry of Education, Government of People’s Republic of Bangladesh, vide their letter
  no. sha 9168 (part) 313, dated, 18th May 2002 and Board of Intermediate and Secondary Education, Dhaka, Letter no. 1079 dated
  24/07/2002. Our College Code Number is 1056 & EIIN: 108572, Milestone Preparatory KG School is also approved by the
  Government, School Code Number is 1098.</p>
      <div class="row">
        <div class="col-md-4 crl1 about_grid">
          <i class="fas fa-university"></i>
          <h4>Academic</h4>
          <p>Our Academic Excellency</p>
          <button type="button" class="more-bttn" data-toggle="modal" data-target="#exampleModalCenter">
            Read More
          </button>
        </div>
        <div class="col-md-4 crl2 about_grid">
          <i class="fas fa-tags"></i>
          <h4>Admission</h4>
          <p>Start Your Life in Milestone</p>
          <button type="button" class="more-bttn" data-toggle="modal" data-target="#exampleModalCenter">
            Read More
          </button>
        </div>
        <div class="col-md-4 crl3 about_grid">
          <i class="fas fa-graduation-cap"></i>
          <h4>Courses</h4>
          <p>See What We Offer</p>
          <button type="button" class="more-bttn" data-toggle="modal" data-target="#exampleModalCenter">
            Read More
          </button>
        </div>
      </div>
    </div>
  </div>

  <!-- Services -->
        <div class="services">
<div class="container">
      <h1>Services</h1>
      <h3>Best Services</h3>
      <p>We provide education with quality and ensure best quality education for you.</p>
  <div class="row custom-row">
    <div class="col-mid-6">
      <div class="services-grid">
        <div class="row">
          <div class="col-sm-12 col-md-2 services-grid1">
            <div class="services-grid-left">
           <i class="fa fa-flask"></i>
            </div>
          </div>
          <div class="col-sm-12 col-md-2 services-grid1 services-grid-right">
            <h5>Our Services</h5>
          </div>
          <div class="col-sm-12 col-md-6 services_grid2">
            <p><span><i class="fas fa-long-arrow-alt-right"></i></span>Check our services</p>
            <p><span><i class="fas fa-long-arrow-alt-right"></i></span>Check our services</p>
            <p><span><i class="fas fa-long-arrow-alt-right"></i></span>Check our services</p>
            <button type="button" class="more-details" data-toggle="modal" data-target="#exampleModalCenter">
              Read More
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="col-mid-6">
      <div class="services-grid">
        <div class="row">
          <div class="col-sm-12 col-md-2 services-grid1">
            <div class="services-grid-left">
           <i class="fa fa-flask"></i>
            </div>
          </div>
          <div class="col-sm-12 col-md-2 services-grid1 services-grid-right">
            <h5>Our Services</h5>
          </div>
          <div class="col-sm-12 col-md-6 services_grid2">
            <p><span><i class="fas fa-long-arrow-alt-right"></i></span>Check our services</p>
            <p><span><i class="fas fa-long-arrow-alt-right"></i></span>Check our services</p>
            <p><span><i class="fas fa-long-arrow-alt-right"></i></span>Check our services</p>
            <button type="button" class="more-details" data-toggle="modal" data-target="#exampleModalCenter">
              Read More
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="col-mid-6">
      <div class="services-grid">
        <div class="row">
          <div class="col-sm-12 col-md-2 services-grid1">
            <div class="services-grid-left">
           <i class="fa fa-flask"></i>
            </div>
          </div>
          <div class="col-sm-12 col-md-2 services-grid1 services-grid-right">
            <h5>Our Services</h5>
          </div>
          <div class="col-sm-12 col-md-6 services_grid2">
            <p><span><i class="fas fa-long-arrow-alt-right"></i></span>Check our services</p>
            <p><span><i class="fas fa-long-arrow-alt-right"></i></span>Check our services</p>
            <p><span><i class="fas fa-long-arrow-alt-right"></i></span>Check our services</p>
            <button type="button" class="more-details" data-toggle="modal" data-target="#exampleModalCenter">
              Read More
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="col-mid-6">
      <div class="services-grid">
        <div class="row">
          <div class="col-sm-12 col-md-2 services-grid1">
            <div class="services-grid-left">
           <i class="fa fa-flask"></i>
            </div>
          </div>
          <div class="col-sm-12 col-md-2 services-grid1 services-grid-right">
            <h5>Our Services</h5>
          </div>
          <div class="col-sm-12 col-md-6 services_grid2">
            <p><span><i class="fas fa-long-arrow-alt-right"></i></span>Check our services</p>
            <p><span><i class="fas fa-long-arrow-alt-right"></i></span>Check our services</p>
            <p><span><i class="fas fa-long-arrow-alt-right"></i></span>Check our services</p>
            <button type="button" class="more-details" data-toggle="modal" data-target="#exampleModalCenter">
              Read More
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
  </div>

<hr/>
        <footer>
            <p>&copy; {{ year }} - Milestone Automation</p>
        </footer>

  <script src="https://code.jquery.com/jquery-2.2.3.min.js" integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo=" crossorigin="anonymous"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.10.0/js/lightbox.min.js"> </script>
  <script type="text/javascript" src="{% static 'js/jquery.flexslider.js' %}"></script>

  <script type="text/javascript">
    $(function(){
      SyntaxHighlighter.all();
    });
    $(window).load(function(){
      $('.flexslider').flexslider({
        animation: "slide",
        start: function(slider){
          $('body').removeClass('loading');
        }
      });
    });
  </script>
</body>
</html>